[tox]
minversion = 3.0.0
skipsdist = True
envlist = clean,py36,py39,py311,report

[testenv]
usedevelop = True
install_command = pip install {opts} {packages}
deps = 
        -r{toxinidir}/requirements.txt
        -r{toxinidir}/test-requirements.txt
commands = coverage run -m pytest hepscore -v --junitxml=report.xml {posargs}

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage xml
    coverage report -m

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:pep8]
basepython = python3
deps = {[testenv]deps}
commands = pylint --exit-zero -j 0 {posargs} {toxinidir}/hepscore

[testenv:bandit]
basepython = python3
commands = bandit -r hepscore -ll --exclude tests --skip B108

[testenv:badge]
deps = anybadge
commands = anybadge --overwrite --label "code quality" --value={posargs} --file=public/badges/pep8.svg 4=red 6=orange 8=yellow 10=green
