archive_images:
  stage: archive-images
  image: gitlab-registry.cern.ch/hep-benchmarks/hep-workloads/hep-workload-builder-multiarch:latest
  retry: 0
  tags:
    - $ARCH
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "BMK-1434"
  variables: 
    default_config: ${CI_PROJECT_DIR}/hepscore/tests/etc/hepscore_conf_ci_helloworld.yaml
    workdir: /tmp/HEPSCORE/$CI_JOB_ID
    remote_archive: ${CI_WEB_RELEASES}/../images/archives
    destination_folder: ${CI_EOS_RELEASES}/../images/archives
  script:
    - cd $CI_PROJECT_DIR
    - yum install -y python3-pip sshpass
    - python3 -m pip install --upgrade pip 
    - pip3 install .
    - python3 hepscore/archive_images.py -i ${default_config} -w ${workdir} -a ${ARCH} -r ${remote_archive}
    - ls -Rltrh ${workdir}
    - cat ${workdir}/*.json ; echo -e "\n"
    - cat ${workdir}/*_sha256sum.txt ; echo -e "\n"
    - archive_file=`ls ${workdir}/*tar.gz`
    - echo $archive_file
    - SSHPASS=${CI_CPUBMK} sshpass -v -e scp -v -oStrictHostKeyChecking=no ${workdir}/*.tar.gz ${workdir}/*.json ${workdir}/*_sha256sum.txt cpubmk@lxplus.cern.ch:${destination_folder}
    - curl -o retrieved_file ${remote_archive}/${archive_file}
   # - cmp retrieved_file ${archive_file}

  after_script:
    - tar -czf archive_images.tgz /tmp/HEPSCORE/$CI_JOB_ID
  artifacts:
      paths:
        - archive_images.tgz
      expire_in: 1 week
      when: always
  parallel:
    matrix:
      - ARCH: [x86_64, aarch64]

